defaults:
  - logger: base_logger
  - arch: anakin
  - system: q_learning/ff_dqn
  - network: mlp_dqn
  - env: navix/empty_8x8
  - _self_

hydra:
  searchpath:
    - /home/kellen/Projects/phd_thesis/research/stoix/configs
