defaults:
  - logger: base_logger
  - arch: anakin
  - system: gcrl/ff_gcrl
  - network: mlp
  - env: navix/empty_5x5
  - _self_

hydra:
  searchpath:
    - /home/kellen/Projects/phd_thesis/research/stoix/configs
